// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_encrypto/test/infrastructure/repo/save_repo_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_encrypto/infrastructure/data/save_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUnit_0 extends _i1.Fake implements _i2.Unit {}

/// A class which mocks [ISaveDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockISaveDataSource extends _i1.Mock implements _i3.ISaveDataSource {
  MockISaveDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> save({_i5.File? file, String? fileName}) =>
      (super.noSuchMethod(
          Invocation.method(#save, [], {#file: file, #fileName: fileName}),
          returnValue: Future<String>.value('')) as _i4.Future<String>);
  @override
  _i4.Future<_i2.Unit> share(_i5.File? file) =>
      (super.noSuchMethod(Invocation.method(#share, [file]),
              returnValue: Future<_i2.Unit>.value(_FakeUnit_0()))
          as _i4.Future<_i2.Unit>);
}
